unit EditBone.Consts;

interface

const
  EDITBONE_NONE_CHAR = #0;
  EDITBONE_BACKSPACE_CHAR = #8;
  EDITBONE_TAB_CHAR = #9;
  EDITBONE_LINEFEED = #10;
  EDITBONE_CARRIAGE_RETURN = #13;
  EDITBONE_ESCAPE = #27;
  EDITBONE_SPACE_CHAR = #32;

  EDITBONE_STATUS_BAR_PANEL_WIDTH = 88;
  EDITBONE_STATUS_BAR_MACRO_PANEL = 0;
  EDITBONE_STATUS_BAR_CARET_POSITION_PANEL = 1;
  EDITBONE_STATUS_BAR_INSERT_KEYSTATE_PANEL = 2;
  EDITBONE_STATUS_BAR_MODIFIED_INFO_PANEL = 3;
  EDITBONE_STATUS_BAR_HINT_PANEL = 4;

  EDITBONE_TITLE_BAR_MENU = 0;
  EDITBONE_TITLE_BAR_CAPTION = 1;
  EDITBONE_TITLE_BAR_FILENAME = 2;
  //EDITBONE_TITLE_BAR_SPACING1 = 3;
  EDITBONE_TITLE_BAR_ENCODING = 4;
  EDITBONE_TITLE_BAR_SPACING2 = 5;
  EDITBONE_TITLE_BAR_HIGHLIGHTER = 6;
  EDITBONE_TITLE_BAR_SPACING3 = 7;
  EDITBONE_TITLE_BAR_COLORS = 8;
  EDITBONE_TITLE_BAR_SPACING4 = 9;

  EXTENSION_JSON = 1;
  EXTENSION_XML = 2;
  EXTENSION_SQL = 3;

implementation

end.
