unit EditBone.Consts;

interface

const
  EDITBONE_NONE_CHAR = #0;
  EDITBONE_BACKSPACE_CHAR = #8;
  EDITBONE_TAB_CHAR = #9;
  EDITBONE_LINEFEED = #10;
  EDITBONE_CARRIAGE_RETURN = #13;
  EDITBONE_ESCAPE = #27;
  EDITBONE_SPACE_CHAR = #32;

  EDITBONE_MAIN_CAPTION_DOCUMENT = ' - [%s]';
  EDITBONE_STATUS_BAR_PANEL_WIDTH = 88;
  EDITBONE_STATUS_BAR_MACRO_PANEL = 0;
  EDITBONE_STATUS_BAR_CARET_POSITION_PANEL = 1;
  EDITBONE_STATUS_BAR_INSERT_KEYSTATE_PANEL = 2;
  EDITBONE_STATUS_BAR_MODIFIED_INFO_PANEL = 3;
  EDITBONE_STATUS_BAR_HINT_PANEL = 4;
  { Document tab sheet item tags }
  EDITBONE_DOCUMENT_EDITOR_TAG = 0;
  EDITBONE_DOCUMENT_SPLIT_EDITOR_TAG = 1;
  EDITBONE_DOCUMENT_XML_TREE_TAG = 2;
  EDITBONE_DOCUMENT_VERTICAL_SPLITTER_TAG = 3;
  EDITBONE_DOCUMENT_COMBOBOX_SEARCH_TEXT_TAG = 4;
  EDITBONE_DOCUMENT_HORIZONTAL_SPLITTER_TAG = 5;
  EDITBONE_DOCUMENT_SEARCH_PANEL_TAG = 6;
  EDITBONE_DOCUMENT_LABEL_SEARCH_RESULT_COUNT_TAG = 7;

  EDITBONE_TITLE_BAR_MENU = 0;
  EDITBONE_TITLE_BAR_CAPTION = 1;
  EDITBONE_TITLE_BAR_FILE_NAME = 2;
  EDITBONE_TITLE_BAR_SPACING1 = 3;
  EDITBONE_TITLE_BAR_ENCODING = 4;
  EDITBONE_TITLE_BAR_SPACING2 = 5;
  EDITBONE_TITLE_BAR_HIGHLIGHTER = 6;
  EDITBONE_TITLE_BAR_SPACING3 = 7;
  EDITBONE_TITLE_BAR_COLORS = 8;
  EDITBONE_TITLE_BAR_SPACING4 = 9;

implementation

end.
